### ISSUE TITLE
AEMaaCS In-Page Experience Selector Dialog - Account Dropdown not working

### ISSUE THREAD

**Issue by ahmed-musallam** [brightcove/Adobe-AEM-Brightcove-Connector#58]
In version 6.0.0 of the connector (for AEMaaCS) in the **in-page experience component dialog**, I am not able to select an account from the dropdown

after investigating it, looking at the 6.0.0 package and the dialog for the component at path

`/apps/brightcove/components/content/brightcoveexperiences/_cq_dialog/.content.xml`

it seems the issue is a missing class `granite:class="brightcove-dialog-account-dropdown"` on the account field.

Now, latest version of the connector on github does have that class, however, it does not seem to have been released for cloud. Will this be released soon?

**Comment by hngrylobster** [comment]
Thanks, Ahmed. We are working on a new release for later this month with a few fixes and we will include this.

**Comment by ahmed-musallam** [comment]
@hngrylobster I'm curious if the new release is still coming?

I am also curious if there are any upcoming milestones to modernize this implementation and make it AEMaaCS-forward: using newer CUI3 widgets, revamp the API, provide a usable framework to ease custom implementations ..etc

**Comment by hngrylobster** [comment]
I believe this should be fixed with the following release:
https://github.com/brightcove/Adobe-AEM-Brightcove-Connector/releases/tag/6.0.1-cloud

In terms of modernization, I wholeheartedly agree. I would recommend you reach out to Brightcove Engineering or Support directly to get a better idea of their roadmap for this connector.
